# US Data

References : [Chapter 5 : PCE (BEA)](https://www.bea.gov/resources/methodologies/nipa-handbook/pdf/chapter-05.pdf)

Careful to NIPA levels ; the same tables 2.4.3, 2.4.4 and 2.4.5 without the "U" that stands for "Underlying Details" are different aggregation levels. Those one are the most frequently used, while Lansing and Shapiro use the "Underlying Details" tables (129 components).

## Definition
Personal Consumption Expenditures (PCE) is a measure of the spending on goods and services by people of the United States, constructed and reported by the Bureau of Economic Analysis (BEA). According to the BEA, PCE accounts for about two-thirds of domestic spending and is a significant driver of gross domestic product (GDP).

Its main aggregates are...

We collect :
- **Table 2.4.4U :** Price Indexes for Personal Consumption Expenditures by Type of Product
- **Table 2.4.5U :** Personal Consumption Expenditures by Type of Product

chained value (2017=100) of PCE components indices, real and nominal, as well as quantities at a monthly frequency. Data is seasonally adjusted.

In [1]:
# Librairies
import json
import pandas as pd
from fismi import sdxData as sdx
import numpy as np

### Settings

In [ ]:
# Pick the desired level ("4" is the disagregation level used in Shapiro et Al., 2026)
# Authors use Level 4
# State-Space uses Level 2
niv = "4"

### Index sub-components

In [3]:
with open('/Users/lea_gosselin/.openbb_platform/user_settings.json', 'r') as file:
    keys = json.load(file)

In [4]:
url = "https://apps.bea.gov/api/data"
userid = keys["credentials"].get("bea_api_key")

# Load PCE data from BEA

# Query data
price_raw   = sdx.getBeaData("U20404", userid)   # Table 2.4.4U : Price Indexes for Personal Consumption Expenditures by Type of Product
weights_raw = sdx.getBeaData("U20405", userid)   # Table 2.4.5U : Personal Consumption Expenditures by Type of Product

In [5]:
# Load PCE components levels (not available online)
levelPce = pd.read_excel("PCEComponentsLevel.xlsx", dtype={"LineNumber": str, "Level": str})
levelPce[levelPce["Level"]==niv]

,LineNumber,Level,LineDescription,SeriesCode
3,4,2,Motor vehicles and parts,DMOTRA
22,23,2,Furnishings and durable household equipment,DFDHRA
37,38,2,Recreational goods and vehicles,DREQRA
61,62,2,Other durable goods,DODGRA
72,73,2,Food and beverages purchased for off-premi...,DFXARA
103,104,2,Clothing and footwear,DCLORA
112,113,2,Gasoline and other energy goods,DGOERA
119,120,2,Other nondurable goods,DONGRA
151,152,2,Housing and utilities,DHUTRA
171,172,2,Health care,DHLCRA
189,190,2,Transportation services,DTRSRA
208,209,2,Recreation services,DRCARA
233,234,2,Food services and accommodations,DFSARA
251,252,2,Financial services and insurance,DIFSRA
279,280,2,Other services,DOTSRA

In [6]:
# How many components ? 2.4.4
price_raw.loc[price_raw["LineNumber"].isin(levelPce.loc[levelPce["Level"]==niv, "LineNumber"]), ["LineNumber","LineDescription","SeriesCode"]].drop_duplicates()

,LineNumber,LineDescription,SeriesCode
2436,4,Motor vehicles and parts,DMOTRG
16256,23,Furnishings and durable household equipment,DFDHRG
28436,38,Recreational goods and vehicles,DREQRG
47276,62,Other durable goods,DODGRG
56208,73,Food and beverages purchased for off-premises ...,DFXARG
81380,104,Clothing and footwear,DCLORG
88688,113,Gasoline and other energy goods,DGOERG
94372,120,Other nondurable goods,DONGRG
119544,152,Housing and utilities,DHUTRG
134676,172,Health care,DHLCRG
147612,190,Transportation services,DTRSRG
162200,209,Recreation services,DRCARG
181072,234,Food services and accommodations,DFSARG
194680,252,Financial services and insurance,DIFSRG
214248,280,Other services,DOTSRG

In [7]:
# How many components ? 2.4.5
weights_raw.loc[weights_raw["LineNumber"].isin(levelPce.loc[levelPce["Level"]==niv, "LineNumber"]), ["LineNumber","LineDescription","SeriesCode"]].drop_duplicates()

,LineNumber,LineDescription,SeriesCode
2436,4,Motor vehicles and parts,DMOTRC
16256,23,Furnishings and durable household equipment,DFDHRC
28436,38,Recreational goods and vehicles,DREQRC
47276,62,Other durable goods,DODGRC
56208,73,Food and beverages purchased for off-premises ...,DFXARC
81380,104,Clothing and footwear,DCLORC
88688,113,Gasoline and other energy goods,DGOERC
94372,120,Other nondurable goods,DONGRC
120356,152,Housing and utilities,DHUTRC
135488,172,Health care,DHLCRC
148424,190,Transportation services,DTRSRC
163012,209,Recreation services,DRCARC
181884,234,Food services and accommodations,DFSARC
195492,252,Financial services and insurance,DIFSRC
215060,280,Other services,DOTSRC

In [8]:
# Merge data on LineNumber - Index
price_raw.loc[price_raw["LineNumber"].isin(levelPce.loc[levelPce["Level"]==niv, "LineNumber"]), ["LineNumber","LineDescription","SeriesCode"]].drop_duplicates()
price_raw = price_raw.merge(
    levelPce[["LineNumber","Level"]],
    how="left",
    on="LineNumber")
price_raw

,TIME_PERIOD,LineNumber,LineDescription,SeriesCode,DataValue,Level
0,1959-01-01,1,Personal consumption expenditures,DPCERG,15.164,NaN
1,1959-02-01,1,Personal consumption expenditures,DPCERG,15.179,NaN
2,1959-03-01,1,Personal consumption expenditures,DPCERG,15.189,NaN
3,1959-04-01,1,Personal consumption expenditures,DPCERG,15.219,NaN
4,1959-05-01,1,Personal consumption expenditures,DPCERG,15.227,NaN
...,...,...,...,...,...,...
303803,2026-04-01,402,Market-based PCE excluding food and energy,DPCXRG,126.756,NaN
303804,2026-05-01,402,Market-based PCE excluding food and energy,DPCXRG,127.071,NaN
303805,2026-06-01,402,Market-based PCE excluding food and energy,DPCXRG,127.282,NaN
303806,2026-07-01,402,Market-based PCE excluding food and energy,DPCXRG,127.465,NaN
303807,2026-08-01,402,Market-based PCE excluding food and energy,DPCXRG,127.829,NaN

In [9]:
# Merge data on LineNumber - Quantites
weights_raw.loc[weights_raw["LineNumber"].isin(levelPce.loc[levelPce["Level"]==niv, "LineNumber"]), ["LineNumber","LineDescription","SeriesCode"]].drop_duplicates()
weights_raw = weights_raw.merge(
    levelPce[["LineNumber","Level"]],
    how="left",
    on="LineNumber")
weights_raw

,TIME_PERIOD,LineNumber,LineDescription,SeriesCode,DataValue,Level
0,1959-01-01,1,Personal consumption expenditures,DPCERC,306091,NaN
1,1959-02-01,1,Personal consumption expenditures,DPCERC,309554,NaN
2,1959-03-01,1,Personal consumption expenditures,DPCERC,312702,NaN
3,1959-04-01,1,Personal consumption expenditures,DPCERC,312193,NaN
4,1959-05-01,1,Personal consumption expenditures,DPCERC,316130,NaN
...,...,...,...,...,...,...
305427,2026-04-01,402,Market-based PCE excluding food and energy,DPCXRC,16432292,NaN
305428,2026-05-01,402,Market-based PCE excluding food and energy,DPCXRC,16567108,NaN
305429,2026-06-01,402,Market-based PCE excluding food and energy,DPCXRC,16673987,NaN
305430,2026-07-01,402,Market-based PCE excluding food and energy,DPCXRC,16688207,NaN
305431,2026-08-01,402,Market-based PCE excluding food and energy,DPCXRC,16829621,NaN

In [10]:
# Weights PCE (share of the expenditure in the total, as current $) 
df_price   = price_raw[price_raw["Level"]==niv].drop_duplicates(subset=["TIME_PERIOD","LineNumber"]).pivot(index="TIME_PERIOD", columns="LineDescription", values="DataValue")
df_weights = weights_raw[weights_raw["Level"]==niv].drop_duplicates(subset=["TIME_PERIOD","LineNumber"]).pivot(index="TIME_PERIOD", columns="LineDescription", values="DataValue")

### Weights

The share of expenditures in the total index is expressed in current Dollar, such as : 
$$
w_{i,t} = \frac{PCE_{i,t}}{PCE_{Total,t}}
$$

In [11]:
# Compute weights over time
df_weights = df_weights.div(df_weights.sum(axis=1, skipna=True),  axis=0)

In [12]:
# PCE data
PCE = price_raw[
    (price_raw["SeriesCode"]=="DPCERG")
    ].drop_duplicates(subset=["TIME_PERIOD","LineNumber"]).pivot(index="TIME_PERIOD", columns="LineDescription", values="DataValue")
PCE

LineDescription  Personal consumption expenditures
TIME_PERIOD
1959-01-01                                  15.164
1959-02-01                                  15.179
1959-03-01                                  15.189
1959-04-01                                  15.219
1959-05-01                                  15.227
...                                            ...
2026-04-01                                 130.672
2026-05-01                                 131.241
2026-06-01                                 131.106
2026-07-01                                 131.172
2026-08-01                                 131.579

[812 rows x 1 columns]

In [14]:
df_price

LineDescription,Clothing and footwear,Financial services and insurance,Food and beverages purchased for off-premises consumption,Food services and accommodations,Furnishings and durable household equipment,Gasoline and other energy goods,Health care,Housing and utilities,Motor vehicles and parts,Other durable goods,Other nondurable goods,Other services,Recreation services,Recreational goods and vehicles,Transportation services,Personal consumption expenditures
TIME_PERIOD,,,,,,,,,,,,,,,,
1959-01-01,51.205,9.913,16.034,9.287,56.465,9.793,5.440,11.421,30.190,33.292,15.431,10.654,12.350,331.285,12.017,15.164
1959-02-01,51.194,9.933,15.973,9.335,56.434,9.987,5.450,11.430,30.235,33.343,15.429,10.649,12.415,331.295,12.048,15.179
1959-03-01,51.224,9.933,15.942,9.351,56.485,9.982,5.459,11.439,30.315,33.330,15.442,10.661,12.508,331.015,12.105,15.189
1959-04-01,51.310,9.916,15.898,9.410,56.648,10.049,5.483,11.486,30.344,33.360,15.504,10.657,12.590,329.991,12.140,15.219
1959-05-01,51.366,9.911,15.862,9.464,56.726,9.994,5.511,11.495,30.442,33.353,15.538,10.643,12.610,329.640,12.153,15.227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-01,107.276,146.422,131.823,142.128,114.678,168.006,123.852,144.407,126.524,101.903,116.519,123.452,134.347,91.423,143.363,130.672
2026-05-01,107.321,147.273,131.902,142.552,114.187,178.883,124.208,144.856,126.280,102.746,116.224,124.323,134.617,91.815,144.623,131.241
2026-06-01,107.135,147.739,132.234,142.442,114.347,162.363,124.629,145.059,126.337,100.384,116.541,124.524,134.428,92.297,145.455,131.106
2026-07-01,107.008,147.692,132.126,142.336,113.324,158.002,124.870,145.443,126.862,100.947,116.483,124.530,134.381,93.447,145.672,131.172
2026-08-01,107.179,147.999,132.167,143.015,113.350,164.878,125.148,145.650,126.838,100.656,116.390,125.607,134.319,93.783,147.776,131.579

In [13]:
# Add DPCERG : PCE total

# Append HICP Total
df_price = df_price.merge(
    PCE,
    how="left",
    left_index=True,
    right_index=True
)
df_price.to_parquet(f"input/USItemsLvl{niv}.parquet")

# Weights...
df_weights.to_parquet(f"input/USnormedWeightsLvl{niv}.parquet")